# Generated by Django 4.2.3 on 2023-07-26 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movierecommender', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchedList',
            new_name='WatchList',
        ),
    ]
