# Generated by Django 4.2.3 on 2023-07-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommender', '0004_rename_watchedlist_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
